# Generated by Django 3.0.6 on 2020-05-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortnerlogic', '0002_clickcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickCount',
        ),
    ]
