# Generated by Django 3.0.6 on 2020-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortnerlogic', '0003_delete_clickcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clickcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
