# Generated by Django 3.0.6 on 2020-05-28 06:03

from django.db import migrations, models
import shortnerlogic.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortnerlogic', '0004_link_clickcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shorturl',
            field=models.CharField(blank=True, default=shortnerlogic.models.generateShortUrl, max_length=100, null=True),
        ),
    ]
